### ISSUE TITLE
Split screen for instructor

### ISSUE THREAD

**Issue by atombaby** [fredhutchio/intro-bioinformatics#11]
The SWC mailing list had a post from this person- she used tmux's split screen and some scripts to keep a running history of the last five commands at the top of the shell screen.

http://blog.rgaiacs.com/2015/06/18/swc_shell.html

Might be useful to incorporate.

**Comment by metasoarous** [comment]
Ohh... that's brilliant. Good find! I'll start doing that.

**Comment by metasoarous** [comment]
This is gonna be a little tricky since we're already using tmux in the course, and this tool is based on tmux. Still, I think there are some good ideas from this we can harvest.
