### ISSUE TITLE
Make a bioteach user group

### ISSUE THREAD

**Issue by metasoarous** [fredhutchio/intro-bioinformatics#12]
@atombaby - This would make it easier for instructors to throw files in their from their normal accounts. Make sense?

**Comment by matsen** [comment]
Where would these files live? In the bioteach account homedir?

**Comment by metasoarous** [comment]
Well, just for _any_ files we needed to move over there. But yes. My guess is there is already a (default) `bioteach` group created when the user was created (could be wrong though). So it's really just a matter of adding people to that group. That way we could move over dotfiles, data, etc. without having to `scp`. Minor convenience, easily won (I think).
