### ISSUE TITLE
sshfs from homebrew may need a few more steps

### ISSUE THREAD

**Issue by bcclaywell** [fredhutchio/intro-bioinformatics#13]
On a student's MacBook running Yosemite today, getting sshfs installed required the following:

```
$ brew install Caskroom/cask/osxfuse
$ brew tap homebrew/fuse
$ brew install sshfs
```

(For some reason I didn't have to tap homebrew/fuse on my MacBook.)

It's probably also worth noting that the user may need to supply a username to the sshfs command if their Mac username is different than their Hutch username.

**Comment by matsen** [comment]
Thanks for this, Brian. I've used it with @janetmatsen. 

@atombaby and @metasoarous -- I've been helping a HS student get going in our group, and the simplest solution ended up being installing XQuartz. Then, if they `ssh -X`, they can have their Terminal and GEdit too.

@bcclaywell pointed me to http://mobaxterm.mobatek.net/ for the Windows folk out there. Thoughts?

**Comment by metasoarous** [comment]
That's an interesting idea. As long as they're on campus this should work great. But if folks try to do this at home, it'll be painful (I've never gotten X to be responsive at home, tunnelling through snail).

I rather like Brian's suggestion of using nano from the perspective of getting people to think of the shell as all they need (and highlighting the value of tmux). But then again, it's not as pleasant an experience for writing code as gedit/whatevs. So I'm a little torn here.

We should just extend the course and teach them vim... :smiling_imp:

**Comment by metasoarous** [comment]
As discussed offline, we've decided to go the way of nano. Closing this issue.
