### ISSUE TITLE
python2 versus python3

### ISSUE THREAD

**Issue by atombaby** [fredhutchio/intro-bioinformatics#15]
There is apparently some significant momentum behind python3 adoption.  There's [this survey](http://astrofrog.github.io/blog/2015/05/09/2015-survey-results/) which shows a non-trivial uptick in use, particularly amongst Windows users (whodathunkit?).  I think something that is also notable is that the Software Carpentry project is [going to start teaching 3](https://github.com/swcarpentry/python-novice-inflammation/issues/127) in upcoming releases.

So I know, barn doors, cows, close.  However, I'm thinking we need to start looking towards starting down the path towards python 3.  Maybe for the next iteration?  Or maybe a python3 workshop independent of this?

**Comment by matsen** [comment]
:+1: I don't think it's time to have it be in the core instruction until it's the default on most systems, though I think suggesting that it will be soon would be better than saying that nobody uses it.

**Comment by metasoarous** [comment]
I fully agree.
