### ISSUE TITLE
Formalize the sketching/brainstorming process a little bit for problems like `unique_pairs`

### ISSUE THREAD

**Issue by metasoarous** [fredhutchio/intro-bioinformatics#27]
- Asked students to solve the problem
- Had them describe in broad strokes
- Drew sketches on whiteboard

Students liked this and said there should be more throughout all the classes. Would be good to formalize that process a little bit more; that is, sketch out ahead of time what it will look like, so it doesn't feel so impromptu.

**Comment by matsen** [comment]
I like this!

**Comment by metasoarous** [comment]
I've added a section to the first class on Polya's problem solving techniques, which I think fits nicely. May adjust things in some of the other classes to fit, but probably mostly in delivery and guidance wrt the in class exercises.
