### ISSUE TITLE
intro-bio module broken?

### ISSUE THREAD

**Issue by metasoarous** [fredhutchio/intro-bioinformatics#38]
@atombaby - Students yesterday were unable to load the intro-bio module. @bcclaywell said that there were some changes made to the module system, but that it shouldn't have affected the intro-bio module. Was something overlooked in this perhaps?

**Comment by atombaby** [comment]
@bmcgough some of that has been redone (vis the switch to lmod, easybuild modules), though all of the existing modules should have come over.  I don't recall how the `intro-bio` module was implemented: I don't see it in our module repository (the `/app` modules).

**Comment by metasoarous** [comment]
OK. Should we just rebuild it then? I think I should be able to compile a list of what is needed.

**Comment by bmcgough** [comment]
Found it. It was in an unexpected location and has been moved to our standard modulefile location (/app/Modules/modulefiles). The Lmod system cache has been updated and intro-bio is `module load`-able now.

**Comment by metasoarous** [comment]
Wonderful! Thanks so much!
