### ISSUE TITLE
FastTree is not on the rhinos

### ISSUE THREAD

**Issue by matsen** [fredhutchio/intro-bioinformatics#4]

**Comment by matsen** [comment]
Also no `nw_display`

**Comment by metasoarous** [comment]
Should we just set them up with a bashrc or zshrc? Then we could point them to matsengrp bin right? Or would they need group permissions?

**Comment by matsen** [comment]
Couldn't point them to matsengrp bin, because of perms. 

I think that we should have them install everything we want for the course on the rhinos. Shall we see if we can cut down that list?

**Comment by atombaby** [comment]
Shouldn't be an issue to add both to /app. Might be a good way to introduce
module as well.

**Comment by matsen** [comment]
Thanks, @atombaby ! Perhaps we could have one for the course.

@metasoarous: do you think that you will have much other software that we should bundle into a module?

**Comment by atombaby** [comment]
@matsen @metasoarous I've got FastTree and a module-d version of muscle installed (there's one that's part of the system binaries as well).

Having a little struggle with `nw_display`.  Is that part of the Newick Utilities (Junier,Zdobnov)?  Is [this](https://github.com/tjunier/newick_utils) the right source?

**Comment by matsen** [comment]
Yep! Ascii art gorgeousness. Thanks, Michael!

**Comment by matsen** [comment]
Releases at http://cegg.unige.ch/newick_utils

**Comment by metasoarous** [comment]
Not really sure yet how much other stuff I'll want to introduce.

**Comment by metasoarous** [comment]
At the very least csvkit, but I can let you know of others as I work through designing the courses.

**Comment by matsen** [comment]
(csvkit is avail via pip)

**Comment by metasoarous** [comment]
@atombaby: Can you please install csvkit and alnvu for us for the next class as well?

**Comment by atombaby** [comment]
@metasoarous I've put csvkit in the python2 install directory, so we'll need to "module load python2".  I'm happy to do alnvu, but can you tag a release for me to install from?

**Comment by atombaby** [comment]
@metasoarous  Nevermind- I overlooked the 0.1.0 tag.  I've installed that as its own module for python 2.7.8:

```
module load alnvu/0.1.0
```

Which will load python 2.7.8 as well.

**Comment by metasoarous** [comment]
Fabulous! Thanks @atombaby

**Comment by matsen** [comment]
Would it be worth setting up a module for the course?

**Comment by atombaby** [comment]
Probably useful, but likely more useful to teach .modulerc files.  I'll
write something up on scicomp on creating those.

What would you want in a course module?

**Comment by matsen** [comment]
Well, I was just thinking that it could work to have one that loaded all the software in the examples. But doing so individually is fine.

@metasoarous I assume you are going to be updating the slides to give examples of loading modules?

**Comment by metasoarous** [comment]
I think one that loaded everything necessary would be ideal. But if that's a hassle, it's not a big deal.

Yeah, I'll update...

**Comment by atombaby** [comment]
It's not that big of a deal- I'll put one together just so that we can save
some typing

we need:
- python2
- csvkit (included with above)
- alnvu
- ?

**Comment by atombaby** [comment]
mrg@rhino01[~]: module load intro-bio
Using already loaded python
mrg@rhino01[~]: module list
Currently Loaded Modulefiles:
  1) python2/2.7.8(default)   4) newick_utils/1.6
  2) alnvu/0.1.0              5) FastTree/2.1.8
  3) intro-bio                6) muscle/3.8.31

I'll add the modulefile to the repository and issue a pull request

**Comment by matsen** [comment]
:+1:

**Comment by metasoarous** [comment]
Wonderful! Thanks!
