### ISSUE TITLE
Vanilla instructor account?

### ISSUE THREAD

**Issue by metasoarous** [fredhutchio/intro-bioinformatics#6]
@atombaby - Do you think it would be possible to set up a `csmall2` (or some such) user that wouldn't have things so customized? Might lead to less confusion, but I don't know how much red tape there is on that sort of thing. Thoughts?

**Comment by atombaby** [comment]
I've requested a system account called "bioteach" that we'll set up with SSH authorized keys for anyone needing to use this account.

I'd like to keep dot-files in git local to that account, though you'd be welcome to create your own dot-files in this repo and apply them for the course (i.e. remove/replace the existing .bashrc) as we can just refresh a base dot-file from git.

**Comment by metasoarous** [comment]
That sounds great Michael; thanks so much. I'll send you my public key in a
bit.

**Comment by atombaby** [comment]
The account has been created- just waiting on home directory.

**Comment by atombaby** [comment]
Ok, homedir and skeleton are set up.  Authorized keys are present, you should be able to:

```
ssh bioteach@rhino
```

with no password.

**Comment by matsen** [comment]
Here is mine: https://keybase.io/ematsen
