### ISSUE TITLE
seqmagick on intro-bio?

### ISSUE THREAD

**Issue by metasoarous** [fredhutchio/intro-bioinformatics#8]
@atombaby - I know it's a little late for, but it would be nice if students could play with this on their own: http://fhcrc.github.io/seqmagick/

**Comment by atombaby** [comment]
I've installed from tag '0.6.0' and added to the intro-bio module.  I haven't exhaustively tested seqmagick, but it starts and prints help.

**Comment by metasoarous** [comment]
Awesome! Thanks.
